[package]
name = "firefly-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
core2 = { version = "0.4.0", default-features = false }
crc32fast = { version = "1.4.2", default-features = false }
embedded-graphics = "0.8.1"
embedded-hal = { version = "1.0.0", default-features = false }
embedded-io = { version = "0.6.1", default-features = false }
firefly-device = { path = "../firefly-device" }
firefly-meta = "0.1.2"
heapless = "0.8.0"
libflate = { version = "2.1.0", default-features = false }
wasmi = { git = "https://github.com/wasmi-labs/wasmi", default-features = false }
