[package]
name = "firefly-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
firefly-meta = "0.1.2"
firefly-device = { path = "../firefly-device" }
embedded-graphics = "0.8.1"
embedded-graphics-transform = "0.1.0"
embedded-hal = { version = "1.0.0", default-features = false }
embedded-io = { version = "0.6.1", default-features = false }
rtic-time = { version = "1.3.0", default-features = false }
wasmi = { git = "https://github.com/wasmi-labs/wasmi", default-features = false }
heapless = "0.8.0"
crc32fast = { version = "1.4.2", default-features = false }
