[package]
name = "firefly-runtime"
version = "0.1.0"
rust-version = "1.82.0"
edition = "2021"

[dependencies]
core2 = { version = "0.4.0", default-features = false }
crc32fast = { version = "1.4.2", default-features = false }
embedded-graphics = "0.8.1"
embedded-io = "0.6.1"
firefly-audio = "0.2.0"
# firefly-hal = { git = "https://github.com/firefly-zero/firefly-hal" }
firefly-hal = { path = "../../firefly-hal" }
firefly-types = { version = "0.4.0" }
heapless = { version = "0.8.0", features = ["serde"] }
libflate = { version = "2.1.0", default-features = false }
postcard = "1.0.8"
serde = { version = "1.0.203", default-features = false, features = ["derive"] }
wasmi = { version = "0.40.0", default-features = false }
