[package]
name = "firefly-runtime"
version = "0.1.0"
rust-version = "1.89.0"
edition = "2021"

[dependencies]
embedded-graphics = "0.8.1"
embedded-io = "0.6.1"
firefly-audio = "0.2.1"
firefly-hal = "0.3.0"
firefly-types = { version = "0.7.1" }
heapless = { version = "0.9.2", features = ["serde"] }
micromath = "2.1.0"
postcard = "1.0.8"
# Use crates.io version when >0.14.1 is released.
# https://github.com/kennytm/qrcode-rust/pull/73
qrcode = { git = "https://github.com/kennytm/qrcode-rust.git", default-features = false }
serde = { version = "1.0.203", default-features = false, features = ["derive"] }
wasmi = { version = "1.0.6", default-features = false }
